dist: bionic
language: node_js
cache: yarn
node_js:
  - 'node'
  - 'lts/*'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn --frozen-lockfile
after_failure:
- yarn build -- --inspect
script:
- yarn lint
- yarn build
- yarn test
after_success: yarn codecov
